ALTER TABLE users
	ADD COLUMN IF NOT EXISTS usage_5h_cost_usd NUMERIC(30, 12) NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS usage_7d_cost_usd NUMERIC(30, 12) NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS usage_5h_started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	ADD COLUMN IF NOT EXISTS usage_7d_started_at TIMESTAMPTZ NOT NULL DEFAULT now();

DROP TABLE IF EXISTS usage_daily;
